MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: "./models/swin_unet/pretrained_ckpt/swin_tiny_patch4_window7_224.pth"
  DROP_RATE: 0.2
  NUM_CLASSES: 14
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
#    DEPTHS: [ 2, 2, 2, 2 ]
#    DECODER_DEPTHS: [ 2, 2, 2, 1]
    DEPTHS: [ 2, 2, 6, 2 ]
    DECODER_DEPTHS: [ 2, 2, 6, 2]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    MLP_RATIO: 4.
    WINDOW_SIZE: 4 # 7
    PATCH_SIZE: 16
    IN_CHANS: 3
    QKV_BIAS: True
    QK_SCALE: null
    APE: False
    PATCH_NORM: True